### ISSUE TITLE
Deprecation notice (LOCALE flag)

### ISSUE THREAD

**Issue by lordkada** [eric-cc-su/PyAiml2#5]
.../pyaiml2/aiml/PatternMgr.py:29: DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6

**Comment by eric-cc-su** [comment]
@lordkada acknowledged. Beginning work on 3.6 compatibility

**Comment by lordkada** [comment]
thx! ;-)

**Comment by eric-cc-su** [comment]
@lordkada fix pushed to master in [PR 6](https://github.com/eric-cc-su/PyAiml2/pull/6)

**Comment by lordkada** [comment]
Great!
